# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
# Modify below for your local machine!
# Temporarily target "all" for running src/Data.cpp

BOARD_TAG    = uno
MONITOR_PORT = /dev/ttyACM0
ARDUINO_DIR  = /opt/arduino-1.6.12
ARDUINO_LIBS = SD SPI

include /usr/share/arduino/Arduino.mk
